### ISSUE TITLE
No Configurator

### ISSUE THREAD

**Issue by AJEvans3** [jasondefuria/Honeywell-Lyric#4]
I installed the custom component in the HACS Store on my home assistant and restarted the server the configurator is not popping up under notifications. I also do not see the Honeywell Lyric component under Configuration> Integrations.

**Comment by residencekedda** [comment]
+1

**Comment by maadhader** [comment]
+2..got it working... :)

**Comment by jasondefuria** [comment]
Sorry, been busy with having to go back to school. 

You installed this in custom repository in HACS, yes? There should not be a configurator to come up, like previous versions. It should come up in the Configuration--> Integrations. Did you restart after install? 

Make sure you are using the latest release, and not the testing branch!

**Comment by jasondefuria** [comment]
Take a look here- native integration is coming. My integration will be deprecated as the native that does asyncio will be better in every shape and form.

Great work by @Timmo001 https://github.com/home-assistant/core/pull/39695
